version: "2"

services:
  portus:
    image: opensuse/portus:head
    depends_on:
      - background
      - portus-db
    env_file:
      - portus.env
    environment:
      # Machine name
      PORTUS_MACHINE_FQDN_VALUE: ${MACHINE_FQDN}
      # Login
      PORTUS_DB_PASSWORD: ${SECRET_MASTER_PASSWORD}
      PORTUS_PASSWORD: ${SECRET_MASTER_PASSWORD}
      PORTUS_SECRET_KEY_BASE: ${SECRET_KEY_BASE}

      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_RELATIVE_URL_ROOT: /portus
    links:
      - portus-db
    volumes:
      - certificates:/certificates:ro
      - portus-static:/srv/Portus/public

  background:
    image: opensuse/portus:head
    depends_on:
      - portus-db
    env_file:
      - portus.env
    environment:
      # Machine name
      PORTUS_MACHINE_FQDN_VALUE: ${MACHINE_FQDN}
      # Login
      PORTUS_DB_PASSWORD: ${SECRET_MASTER_PASSWORD}
      PORTUS_PASSWORD: ${SECRET_MASTER_PASSWORD}
      PORTUS_SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      # Theoretically not needed, but cconfig's been buggy on this...
      CCONFIG_PREFIX: PORTUS
      # Activates background mode
      PORTUS_BACKGROUND: "true"
    links:
      - portus-db
    volumes:
      - certificates:/certificates:ro

  portus-db:
    image: library/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_DATABASE: portus_production
      # Again, the password shouldn't be handled like this.
      MYSQL_ROOT_PASSWORD: ${SECRET_MASTER_PASSWORD}
    volumes:
      - portus-db:/var/lib/mysql

  registry:
    image: registry:2.6
    env_file:
      - registry.env
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${MACHINE_FQDN}/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - registry:/var/lib/registry
      - certificates:/secrets:ro
    links:
      - portus

  nginx:
    build: ./nginx
    image: ${MACHINE_FQDN}/infrastructure/portus-nginx
    environment:
      MACHINE_FQDN: ${MACHINE_FQDN}
    volumes:
      - certificates:/secrets:ro
      - portus-static:/srv/Portus/public:ro
    links:
      - registry
      - portus

volumes:
  portus-static:
  portus-db:
  registry:
  certificates:
    external: true
    # driver: rancher-nfs
